import logging
import os
import subprocess
import socket

import SimpleITK as sitk


def run_cranio_preprocessing(
    t2_path: str, logger: logging.Logger, device: str = "cpu"
) -> str:

    logger.info("Running cranio preprocessing")

    # n4 correction
    image_path_n4 = apply_n4_correction(image_path=t2_path, logger=logger)

    # skull stripping
    image_path_masked = apply_skull_stripping(
        image_path=image_path_n4, logger=logger, device=device
    )

    #log node 
    logger.info(f"Node: {socket.gethostname()}")
    logger.info(f"CUDA_VISIBLE_DEVICES: {os.environ.get('CUDA_VISIBLE_DEVICES')}")

    logger.info("Preprocessing done")

    return image_path_masked


def apply_n4_correction(image_path, logger: logging.Logger):
    logger.info("Running N4 correction")
    logger.info(f"Image path: {image_path}")
    n4_path = image_path.replace(".nii.gz", "_n4.nii.gz")

    if os.path.exists(n4_path):
        logger.info(f"N4 corrected image already exists at: {n4_path}")
        return n4_path

    logger.info("Reading image")
    input_image = sitk.ReadImage(image_path, sitk.sitkFloat32)

    logger.info("Creating mask")
    mask_image = sitk.OtsuThreshold(input_image, 0, 1, 200)

    logger.info("Applying N4 correction")
    bias_corrector = sitk.N4BiasFieldCorrectionImageFilter()
    bias_corrector.AddCommand(
        sitk.sitkIterationEvent, lambda: print_iteration(bias_corrector, logger)
    )
    bias_corrector.SetMaximumNumberOfIterations([40] * 4)
    bias_corrector.SetConvergenceThreshold(0.0000000001)
    bias_corrector.DebugOn()
    bias_corrector.GlobalDefaultDebugOn()
    bias_corrector.SetDebug(True)
    bias_corrector.SetGlobalDefaultDebug(True)

    logger.info(bias_corrector)
    corrected_image = bias_corrector.Execute(input_image, mask_image)

    logger.info("Saving corrected image")
    sitk.WriteImage(corrected_image, n4_path)
    logger.info(f"Saved corrected image to: {n4_path}")

    return n4_path


def apply_skull_stripping(image_path: str, logger: logging.Logger, device: str = "cpu"):
    """
    Applies skull stripping to a given medical image using the HD-BET tool.
    This function takes the path to a medical image file, applies skull stripping
    using the HD-BET tool, and saves the resulting masked image to a new file.
    The function logs the process using the provided logger.
    Args:
        image_path (str): The file path to the input medical image in NIfTI format (.nii.gz).
        logger (logging.Logger): A logger instance to log the process.
    Returns:
        str: The file path to the masked image generated by the skull stripping process.
    """

    logger.info(f"Applying skull stripping to {image_path}")
    masked_path = image_path.replace(".nii.gz", "_masked.nii.gz")

    if os.path.exists(masked_path):
        logger.info(f"Skull stripped image already exists at: {masked_path}")
        return masked_path

    # Run HD-BET
    subprocess.run(
        [
            "python",
            "-m",
            "HD_BET.entry_point",
            "-i",
            image_path,
            "-o",
            masked_path,
            "-device",
            device,
            "--save_bet_mask",
        ]
    )

    logger.info("Finished skull stripping")
    logger.info(f"Masked image saved to: {masked_path}")

    return masked_path


def apply_cropping(logger: logging.Logger):
    logger.info("Applying cropping")
    return None


def print_iteration(filter, logger):
    iteration_number = filter.GetElapsedIterations()
    level_number = filter.GetCurrentLevel()
    rms_error = filter.GetCurrentConvergenceMeasurement()
    logger.info(
        f"Level: {level_number} - Iteration: {iteration_number}, RMS Error: {rms_error}"
    )
