# Generate boxplot-style figure for DSC and NSD (T2 v2.0)
# DSC and NSD is filled in manually (generated by final_metrics_segmentation.py)


import matplotlib.pyplot as plt
import numpy as np

structures = [
    "Right ventricle",
    "Left ventricle",
    "3rd ventricle",
    "4th ventricle",
    "CSP",
    "Total"
]

# DSC
dsc_med = [0.94, 0.94, 0.84, 0.82, 0.00, 0.93]
dsc_q1  = [0.89, 0.89, 0.71, 0.74, 0.00, 0.89]
dsc_q3  = [0.97, 0.97, 0.86, 0.86, 0.47, 0.96]

# NSD
nsd_med = [0.99, 0.99, 0.97, 0.96, 0.00, 0.99]
nsd_q1  = [0.97, 0.96, 0.90, 0.94, 0.00, 0.97]
nsd_q3  = [1.00, 1.00, 0.99, 0.99, 0.72, 0.99]

x = np.arange(len(structures))

# Style similar to example figure
plt.style.use("ggplot")

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

def draw_box(ax, med, q1, q3, title):

    box_color = "#4C72B0"

    for i in range(len(structures)):

        # Box
        ax.add_patch(plt.Rectangle(
            (i - 0.28, q1[i]),
            0.56,
            q3[i] - q1[i],
            facecolor=box_color,
            edgecolor="black",
            alpha=0.75,
            linewidth=1.0
        ))

        # Median line
        ax.plot(
            [i - 0.28, i + 0.28],
            [med[i], med[i]],
            color="black",
            linewidth=2
        )

        # Whiskers
        ax.plot([i, i], [q3[i], min(1.0, q3[i] + 0.03)],
                color="black", linewidth=1)

        ax.plot([i, i], [max(0.0, q1[i] - 0.03), q1[i]],
                color="black", linewidth=1)

        # Whisker caps
        ax.plot([i - 0.10, i + 0.10],
                [min(1.0, q3[i] + 0.03)] * 2,
                color="black", linewidth=1)

        ax.plot([i - 0.10, i + 0.10],
                [max(0.0, q1[i] - 0.03)] * 2,
                color="black", linewidth=1)

        # Median point
        ax.scatter(i, med[i], color="black", s=18, zorder=3)

    ax.set_xticks(x)

    ax.set_xticklabels(
        [
            "Right\nventricle",
            "Left\nventricle",
            "3rd\nventricle",
            "4th\nventricle",
            "CSP",
            "Total"
        ],
        fontsize=11
    )

    ax.set_ylim(0, 1.05)

    ax.set_ylabel("Score")
    ax.set_title(title, fontsize=12)

    ax.grid(True, axis='y', alpha=0.5)
    ax.grid(False, axis='x')

    ax.spines['top'].set_visible(True)
    ax.spines['right'].set_visible(True)

draw_box(axes[0], dsc_med, dsc_q1, dsc_q3, "DSC (T2, v2.0)")
draw_box(axes[1], nsd_med, nsd_q1, nsd_q3, "NSD (T2, v2.0)")

plt.tight_layout()

plt.savefig(
    "T2_dsc_nsd.png",
    dpi=300,
    bbox_inches='tight'
)

plt.close()