#This file generates a boxplot of the DSC and NSD scores
# DSC and NSD is filled in manually (generated by final_metrics_segmentation.py)

import matplotlib.pyplot as plt
import numpy as np

structures = [
    "Right ventricle",
    "Left ventricle",
    "3rd ventricle",
    "4th ventricle",
    "CSP",
    "Total"
]

# DSC
dsc_med = [0.94, 0.94, 0.84, 0.82, 0.00, 0.93]
dsc_q1  = [0.89, 0.89, 0.71, 0.74, 0.00, 0.89]
dsc_q3  = [0.97, 0.97, 0.86, 0.86, 0.47, 0.96]

# NSD
nsd_med = [0.99, 0.99, 0.97, 0.96, 0.00, 0.99]
nsd_q1  = [0.97, 0.96, 0.90, 0.94, 0.00, 0.97]
nsd_q3  = [1.00, 1.00, 0.99, 0.99, 0.72, 0.99]

x = np.arange(len(structures))

fig, axes = plt.subplots(1, 2, figsize=(11, 4))

def draw_box(ax, med, q1, q3, title):
    for i in range(len(structures)):
        color = 'lightgray' if i == 4 else 'black'  # CSP grijs
        
        # box (IQR)
        ax.add_patch(plt.Rectangle(
            (i - 0.2, q1[i]),
            0.4,
            q3[i] - q1[i],
            edgecolor=color,
            facecolor='none',
            linewidth=1.5
        ))
        
        # median lijn
        ax.plot([i - 0.2, i + 0.2], [med[i], med[i]], color=color, linewidth=2)

    ax.set_xticks(x)
    ax.set_xticklabels(structures, rotation=45, ha='right')
    ax.set_ylim(0, 1.05)
    ax.set_title(title)
    ax.set_ylabel("Score")
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

draw_box(axes[0], dsc_med, dsc_q1, dsc_q3, "DSC (T2, v2.0)")
draw_box(axes[1], nsd_med, nsd_q1, nsd_q3, "NSD (T2, v2.0)")

plt.tight_layout()

plt.savefig("T2_dsc_nsd.png", dpi=300, bbox_inches='tight')

plt.close()